/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
        "on-tertiary-fixed-variant": "#3a4858",
        "on-primary-fixed-variant": "#264191",
        "inverse-primary": "#b6c4ff",
        "on-primary-fixed": "#00164e",
        "surface-container": "#eceef0",
        "outline": "#757682",
        "on-secondary": "#ffffff",
        "surface-container-low": "#f2f4f6",
        "on-tertiary-fixed": "#0e1d2b",
        "secondary-container": "#d0e1fb",
        "primary-fixed": "#dce1ff",
        "on-background": "#191c1e",
        "surface-container-high": "#e6e8ea",
        "tertiary-container": "#334151",
        "background": "#f7f9fb",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed-dim": "#b9c8db",
        "primary-fixed-dim": "#b6c4ff",
        "secondary-fixed-dim": "#b7c8e1",
        "outline-variant": "#c5c5d3",
        "error": "#ba1a1a",
        "inverse-surface": "#2d3133",
        "on-surface": "#191c1e",
        "surface-tint": "#4059aa",
        "surface-dim": "#d8dadc",
        "inverse-on-surface": "#eff1f3",
        "secondary-fixed": "#d3e4fe",
        "tertiary": "#1d2b3a",
        "on-error": "#ffffff",
        "surface-variant": "#e0e3e5",
        "primary": "#00236f",
        "on-primary": "#ffffff",
        "tertiary-fixed": "#d5e4f8",
        "on-error-container": "#93000a",
        "on-tertiary": "#ffffff",
        "on-surface-variant": "#444651",
        "primary-container": "#1e3a8a",
        "surface-container-highest": "#e0e3e5",
        "secondary": "#505f76",
        "on-primary-container": "#90a8ff",
        "on-secondary-container": "#54647a",
        "on-tertiary-container": "#9eadc0",
        "on-secondary-fixed-variant": "#38485d",
        "surface": "#f7f9fb",
        "surface-bright": "#f7f9fb",
        "on-secondary-fixed": "#0b1c30",
        "error-container": "#ffdad6"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "stack-lg": "24px",
        "unit": "4px",
        "gutter": "24px",
        "stack-sm": "8px",
        "stack-md": "16px",
        "sidebar-width": "260px",
        "container-margin": "32px"
      },
      "fontFamily": {
        "data-tabular": ["Inter"],
        "display-lg": ["Inter"],
        "title-sm": ["Inter"],
        "label-caps": ["Inter"],
        "headline-md": ["Inter"],
        "body-md": ["Inter"],
        "body-sm": ["Inter"]
      },
      "fontSize": {
        "data-tabular": ["14px", {"lineHeight": "20px", "fontWeight": "500"}],
        "display-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "title-sm": ["18px", {"lineHeight": "28px", "letterSpacing": "0", "fontWeight": "600"}],
        "label-caps": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "headline-md": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "body-md": ["16px", {"lineHeight": "24px", "letterSpacing": "0", "fontWeight": "400"}],
        "body-sm": ["14px", {"lineHeight": "20px", "letterSpacing": "0", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
}
